#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
x=10; while  [ $x -gt 0 ]; do echo "Best School"; x=$((x-1)); if [ $x -eq 1 ]; then echo "Hi"; fi done
