#!/usr/bin/env bash
# This script gives information about the 'school' file
FILE=./school
if test -e "$FILE"
then
    echo school file exists
    if test -s "$FILE"
    then
        echo school file is not empty
    else
        echo school file is empty
    fi
    if test -f "$FILE"
    then
        echo school is a regular file
    fi
else
    echo school file does not exist
fi
