#!/usr/bin/env bash
# Script that creates, displays and delete
echo "ps" > /var/run/myscript.pid
trap "echo I am invincible!!!" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "echo rm /var/run/myscript.pid" SIGQUIT SIGTERM
while true
do
	                echo To infinity and beyond
			                                sleep 2
						done
