#!/usr/bin/env bash
#
x=1
case "$x" in
start)
./manage_my_process &	
echo "$!" > /var/run/my_process.pid
echo "manage_my_process started" ;;
stop)
sudo pkill -f "./manage_my_process"
rm "/var/run/my_process.pid"
echo "manage_my_process stopped" ;;

restart)
sudo pkill -f "./manage_my_process"
rm "/var/run/my_process.pid"
./manage_my_process &
echo "$!" > /var/run/my_process.pid
echo "manage_my_process restarted" ;;

esac
